### ISSUE TITLE
bemClassName doesn't play well with ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by sbichenko** [Sunify/bem-classname#1]
# The problem

I think one of the main use-cases for BEM modifiers in React are transitions. However, this won't work:

```
class SignupForm extends Component {

// ...

// this.className is the bound bemClassName function
<ReactCSSTransitionGroup transitionName={this.className('name', { transitioning: true })} ...>
    <div className={this.className('name')}>
        <label>Name</label>
        <input type="text" placeholder="Last Name" {...name}/>
    </div>
</ReactCSSTransitionGroup>

// ...
}
```

I get `Uncaught Error: Invariant Violation: CSSCore.addClass takes only a single class name. "SignupForm__name SignupForm__name--transitioning-enter" contains multiple classes.`

I'd like to be able to pass only the modifier's class name to the function.
# Proposed backwards-compatible solutions
## Make order of the returned classes a part of the API

At the moment, the order of class names is not documented in the readme. If it were documented that the modifier class name is the last one in the returned string, I could parse the result myself. 

Then, instead of 

```
<ReactCSSTransitionGroup transitionName={this.className('name', { transitioning: true })} ...>
```

I'd do 

```
const className = this.className('name',  { transitioning: true });
const modifierClassName = className.substr(className.lastIndexOf(' ') + 1);
<ReactCSSTransitionGroup transitionName={modifierClassName} ...>
```

I'd probably extract a function to reuse this logic. Which brings me to another solution.
## Helper function

Add a `bemModifierClassName` helper function to the module's exports. It accepts two or three string arguments: `bemModifierClassName(block, modifier)` and `bemModifierClassName(block, element modifier)`. It returns a single class name with modifier.

This way, in my example, instead of 

```
<ReactCSSTransitionGroup transitionName={this.className('name', { transitioning: true })} ...>
```

I'd do 

```
<ReactCSSTransitionGroup transitionName={bemModifierClassName(this.constructor.name, 'name', 'transitioning'} ...>
```

**Comment by sunify** [comment]
Thanks for response!

If you want only one modifier, I think you can do something like this (instead of adding helper function to module):

``` jsx
<ReactCSSTransitionGroup transitionName={this.className('name--transitioning')} ...>
```

What do you think about this workaround?

**Comment by sbichenko** [comment]
Hm, yes, but isn't the point of this function to abstract the creation of BEM class names? Doesn't the abstraction leak that way? E.g. the code "around" it suddenly also knows about how BEM class names are made?

There's also the problem of configuration. BEM users use different ways of denoting blocks, elements and modifiers. For example, I think Yandex uses `_` instead of `--` for modifiers. Some use prefixes, such as `b-` for blocks. You might want to add an ability to configure the naming scheme. Using workarounds like the one you proposed makes the component that uses bemClassName tightly coupled to a particular naming scheme.
